# services:
#   db:
#     image: mysql:8
#     container_name: student_project_db
#     environment:
#       MYSQL_ROOT_PASSWORD: "jaya@123"
#       MYSQL_DATABASE: student_db
#       MYSQL_USER: student
#       MYSQL_PASSWORD: student123
#     ports:
#         - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: unless-stopped

#   backend:
#     build: ./backend
#     container_name: student_project_backend
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db
#     restart: unless-stopped

#   frontend:
#     image: nginx:latest
#     container_name: student_project_frontend
#     ports:
#       - "8080:80"
#     volumes:
#       - ./frontend:/usr/share/nginx/html
#     restart: unless-stopped

# volumes:
#   db_data: {}


# # docker exec -it student_project_db mysql -uroot -pjaya@123
# # docker logs student_project_db

version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: jaya@123
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - student_net

  backend:
    image: student_backend:latest
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - student_net

  frontend:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - student_net

volumes:
  db_data:

networks:
  student_net:


